version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/apps/website"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/apps/cms"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 10
