version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/website"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore(deps): 
    labels:
      - dependencies
  - package-ecosystem: "npm"
    directory: "/apps/cms"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore(deps): 
    labels:
      - dependencies
