version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 10
    post-update-hooks:
      - command: "pnpm install"
  - package-ecosystem: "npm"
    directory: "/apps/website"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 10
    post-update-hooks:
      - command: "pnpm install"
  - package-ecosystem: "npm"
    directory: "/apps/cms"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 10
    post-update-hooks:
      - command: "pnpm install"
