name: linting

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  run-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Install modules
        run: pnpm install
      - name: Run linting
        run: pnpm run lint;
